# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cvrp2

on:
  push:
    branches:
      - main2
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_bd99c78638c544fd9e07904af8784e14 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8e92d764624b4f8997be81afef71785a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_bd99c78638c544fd9e07904af8784e14 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cvrp2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ef567e31215741eb9a9c016086598905 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_bd99c78638c544fd9e07904af8784e14 }}/appsvc/staticsite:${{ github.sha }}'